name: Continuous Integration

on: push

jobs:
  build_test:
    name: Build and Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm test -- --runInBand
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    name: Deploy to GitHub Pages
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          fetch-depth: 0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
